//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMarafons.Table
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class users
    {

        
        [Key]
        public int ID { get; set; }
        public int UID { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int TYPEes { get; set; }

        [ForeignKey("TYPEes")]
    
        public virtual TYPE Type { get; set; }
    }
}
